- type: entity
  name: O'Connaburr, the Irelander
  parent: [BaseItem, BaseGrandTheftContraband]
  id: HosIreLander
  description: An antique copper greatsword, said to have once been wielded to end a great trouble.
  components:
  - type: Sprite
    sprite: _Omu/Objects/Weapons/Melee/irelander.rsi
    state: base
  - type: MeleeWeapon
    animationRotation: -135
    heavyStaminaCost: 15
    wideAnimationRotation: -135
    damage:
      types:
        Slash: 20
        Structural: 15
    soundHit:
      collection: MetalThud
  - type: Wieldable
  - type: IncreaseDamageOnWield
    damage:
      types:
        Slash: 10
        Structural: 40
  - type: StaminaDamageOnHit
    damage: 20
  - type: MeleeThrowOnHit
    distance: 1.5
    speed: 10
  - type: Item
    size: Large
    storedRotation: 45
  - type: Tool
    qualities:
    - Rolling
    speedModifier: 1.25
  - type: Clothing
    quickEquip: true
    slots:
    - back
    - suitstorage
  - type: UseDelay
    delay: 0.25
  - type: UndetectableContraband #Goobstation-Contraband detector
  - type: StealTarget
    stealGroup: WeaponSecHeadSword

- type: entity
  name: warden's rapier
  parent: [ BaseSword, BaseGrandTheftContraband ]
  id: WardenRapier
  description: A thin, elegant sword made for lunging over banana peels.
  components:
  - type: Sprite
    sprite: _Omu/Objects/Weapons/Melee/wardenrapier.rsi
  - type: MeleeWeapon
    angle: 0
    animationRotation: -90
    wideAnimationRotation: -90
    heavyStaminaCost: 2.5
    damage:
      types:
        Piercing: 20 # slightly more than the captain sabre but with less attack speed, idk how high this should really be
    soundHit:
        path: /Audio/Weapons/bladeslice.ogg
  - type: Item
    shape:
    - 0,0,0,3
    storedRotation: -45
  - type: MeleeDash
    emoteOnDash: null
    length: 2
  - type: UseDelay
    delay: 1.5
  - type: Tag
    tags:
    - WardenRapier
  - type: StealTarget
    stealGroup: WeaponEnergyShotgun
  - type: DisarmMalus
  - type: Reflect
    reflectProb: 0.3
    spread: 30

- type: entity
  name: The Wind of the Steppes
  parent: [BaseItem, BaseGrandTheftContraband]
  id: HosOniBlade
  description: As the winds of the highlands cut through the lands and wear them to dust, so too does our people's blade.
  components:
  - type: RestrictedMelee # Omu, its made for Oni, so only Oni can use it.
    whitelist:
      tags:
      - Oni
  - type: Sprite
    sprite: _Omu/Objects/Weapons/Melee/oniglaive.rsi
    state: base
  - type: Clothing
    quickEquip: true
    sprite: _Omu/Objects/Weapons/Melee/oniglaive.rsi
    slots:
    - Back
    - suitStorage
  - type: MeleeWeapon
    range: 2.5
    attackRate: 2.0
    animationRotation: -135
    heavyStaminaCost: 15
    wideAnimationRotation: -135
    damage:
      types:
        Slash: 10
        Structural: 15
    soundHit:
      path: /Audio/Weapons/bladeslice.ogg
  - type: Wieldable
  - type: IncreaseDamageOnWield
    damage:
      types:
        Slash: 10
  - type: Item
    size: Huge #should be ok at this size
    storedRotation: 45
  - type: DisarmMalus
    malus: 0.50 # maybe too much, also might not matter at because in melee range you die
  - type: Tool
    qualities:
    - Prying
    useSound:
      path: /Audio/Items/crowbar.ogg
  - type: Prying
    speedModifier: 1.50
  - type: UseDelay
    delay: 0.25
  - type: StealTarget
    stealGroup: WeaponSecHeadSword
