- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleAsakim
  name: Asakim Role
  components:
  - type: MindRole
    roleType: FreeAgent
    subtype: role-subtype-asakim
    antagPrototype: Asakim
    exclusiveAntag: true
  - type: AsakimRole
  - type: RoleBriefing
    briefing: asakim-role-briefing
